gchq/gaffer-tools

slider/pom.xml, slider/scripts/accumulo_shell.sh, slider/scripts/build_accumulo_package.sh, slider/scripts/common.sh, slider/scripts/deploy_test_cluster.sh, slider/scripts/slider.sh, slider/src/assembly/package.xml
Use pom properties instead of hard coding locations of dependencies in scripts
=> gh-59 Fix slider scripts

python-shell/src/gafferpy/gaffer.py
=> Revert "Gh 94"

deployment/aws/apps/road-traffic/cloudformation/gaffer-road-traffic.yaml, deployment/aws/core/cloudformation/gaffer-slider-emr.yaml, deployment/aws/core/cloudformation/gaffer-with-user.yaml, deployment/aws/core/cloudformation/gaffer-with-web.yaml, deployment/aws/tests/integration-tests/cloudformation/gaffer-integration-tests.yaml, deployment/aws/tests/system-tests/cloudformation/gaffer-system-tests.yaml, slider/scripts/build_accumulo_package.sh
I've tested this PR using the [AWS system test](https://github.com/gchq/gaffer-tools/tree/master/deployment/aws/tests/system-tests) to ensure that it allows Gaffer to be deployed on Accumulo 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0 and 1.8.1
=> Gh 195 slider accumulo 1.8

python-shell/src/gafferpy/gaffer.py, python-shell/src/test/test_gaffer_operations.py
Added the ScoreOperationChain to gaffer.py
Added tests to ensure it is serialised correctly
=> gh-232 - ScoreOperationChain added to python shell

python-shell/src/gafferpy/gaffer.py, python-shell/src/test/test_gaffer_operations.py
Added the optional score field to AddNamedOperation
Added a test that includes the score to ensure it is serialised correctly if present
=> gh-231 - Score field added to AddNamedOperation, test added

NOTICES, ui/README.md, ui/pom.xml, ui/src/main/webapp/app/graph/graph-component.js, ui/src/main/webapp/app/graph/selected-elements/selected-elements-component.js, ui/src/main/webapp/app/navigation/navigation-component.js, ui/src/main/webapp/app/query/operation-selector/operation-selector-component.js, ui/src/main/webapp/app/query/query-component.js, ui/src/main/webapp/app/query/result-count-warning-component.js, ui/src/main/webapp/app/query/seed-manager/seed-manager-component.js, ui/src/main/webapp/app/query/view-builder/view-builder-component.js, ui/src/test/webapp/app/controller-spec.js, ui/src/test/webapp/app/graph/graph-component-spec.js, ui/src/test/webapp/app/graph/selected-elements/selected-elements-component-integration-spec.js, ui/src/test/webapp/app/graph/selected-elements/selected-elements-component-spec.js, ui/src/test/webapp/app/graph/selected-elements/selected-elements-spec.js, ui/src/test/webapp/app/loading/loading-component-spec.js, ui/src/test/webapp/app/navigation/navigation-component-spec.js, ui/src/test/webapp/app/query/directionality-picker/directionality-picker-component-spec.js, ui/src/test/webapp/app/query/operation-selector/operation-selector-component-spec.js, ui/src/test/webapp/app/query/parameter-table/parameter-table-component-spec.js, ui/src/test/webapp/app/query/query-component-spec.js, ui/src/test/webapp/app/query/result-count-warning-component-spec.js, ui/src/test/webapp/app/query/seed-manager/seed-manager-component-integration-spec.js, ui/src/test/webapp/app/query/seed-manager/seed-manager-component-spec.js, ui/src/test/webapp/app/query/view-builder/view-builder-component-integration-spec.js, ui/src/test/webapp/app/query/view-builder/view-builder-component-spec.js
Added tests for the following components: 
* The Query Page
* View Builder
* Operation selector
* Graph
* Selected Elements viewer
* Loading Circle
* Nav Bar
* View Builder
* Seed Manager
* Result Count warning dialog
=> Gh 266 unit test components

mini-accumulo-cluster/pom.xml, mini-accumulo-cluster/src/main/java/uk/gov/gchq/gaffer/miniaccumulocluster/MiniAccumuloClusterWithShellController.java, mini-accumulo-cluster/src/main/java/uk/gov/gchq/gaffer/miniaccumulocluster/MiniAccumuloShellController.java
Applying changes from https://github.com/gchq/gaffer-tools/pull/243
=> gh-242 - updated mini accumulo to 1.8.1

python-shell/src/example.py, python-shell/src/gafferpy/gaffer.py, python-shell/src/test/test_gaffer_functions.py, python-shell/src/test/test_gaffer_functions_it.py, python-shell/src/test/test_gaffer_operations.py
Added the remaining Koryphe functions and a simple test for each.
Small amount of clean-up on some other functions.
=> gh-356 - Koryphe Functions and simple tests added

python-shell/src/gafferpy/gaffer_operations.py, python-shell/src/test/test_gaffer_operations.py
To be merged after/into Gaffer update branch
=> gh-667-updated-GetAsElementsFromEndpoint

ui/src/test/java/uk/gov/gchq/gaffer/ui/QueryBuilderST.java
=> gh-758 Added wait period after entering text

mini-accumulo-cluster/README.md, python-shell/README.md, slider/README.md
changed instances of "```text" to appropriate tag
closes #772
=> DOC:Remove instances of "```text" in README files

performance-testing/performance-testing-aws/src/main/java/uk/gov/gchq/gaffer/performancetesting/aws/PublishAccumuloMetricsToCloudWatch.java, pom.xml
Changes required as part of Accumulo upgrade
=> Gh 827 tools accumulo upgrade

python-shell/src/gafferpy/gaffer_operations.py, python-shell/src/test/test_gaffer_operations.py
Covers issue #822. 
Both operations added to GafferPy with tests.
Also updated the AddNamedOperation class to accept a list of labels as an optional input parameter.
=> Gh 822 Add ChangeGraphAccess and GetAllGraphInfo and update AddNamedOperation

python-shell/src/gafferpy/gaffer_operations.py, python-shell/src/test/test_gaffer_operations.py
Addition to the python shell.
Covered by #452
=> Gh 452 - Added ChangeGraphId operation and test

python-shell/src/gafferpy/gaffer_core.py
=> gh-877 Replace is with == when used with literals

ui/src/test/webapp/app/previous-queries/my-queries-component-spec.js
=> Gh 883 Removed broken test for a getter as is unnecessary anyway

cd/verify.sh
=> gh-893 Changed nvm install version for analytics-ui test

python-shell/src/gafferpy/gaffer_operations.py, python-shell/src/test/test_gaffer_operations.py
=> Gh 884 Added include_partial and conditional arguments to GetWalks

python-shell/src/gafferpy/gaffer_operations.py
=> Updated logic for conditional handling of None values

.github/workflows/update-gaffer-version.yaml
=> Gh 908 fix update gaffer typo

.github/workflows/update-gaffer-version.yaml
=> gh-914 Fixed updating gaffer typo

NOTICES, pom.xml, python-shell/src/__init__.py, python-shell/src/gafferpy/__init__.py
=> gh-912 Updated Gaffer version to 1.17.1

.github/workflows/release.yaml, .github/workflows/release_standalone.yaml
Also removed unused `~/.m2/repository` cache
- Resolve #916
=> Gh 916 Added job to change gaffer tools version

fish-bowl/fishbowl/connector.py, python-shell/README.md, python-shell/src/gafferpy/gaffer_connector.py, python-shell/src/gafferpy/gaffer_connector_requests.py
=> gh-910 Fixed gafferpy connector warnings and updated some docs

ui/pom.xml
Fixes duplicate dependency 
- Resolve #922
=> gh-922 Removed duplicate map-store dependency in ui pom

.github/workflows/continuous-integration.yaml
Should clean up xvfb and stop jasmine tests hanging
- Resolve #924
=> gh-924 Added job to clean up xvfb

NOTICES, pom.xml, python-shell/src/__init__.py, python-shell/src/gafferpy/__init__.py
=> gh-919 Updated Gaffer version to 1.18.0

python-shell/src/gafferpy/gaffer_operations.py
=> gh-931: Removed duplicate gafferpy operation

python-shell/README.md
=> Update example files in Gafferpy README.md

NOTICES, pom.xml, python-shell/src/__init__.py, python-shell/src/gafferpy/__init__.py
=> Revert "Updated Gaffer version to 1.19.0"

python-shell/README.md, python-shell/src/gafferpy/gaffer_binaryoperators.py, python-shell/src/gafferpy/gaffer_functions.py, python-shell/src/test/test_gaffer_functions.py
=> gh-940: Added some functions to gafferpy

python-shell/src/gafferpy/gaffer_operations.py, python-shell/src/test/test_gaffer_operations.py
=> gh-704: Added federated graphId helper to Operation options

.github/workflows/continuous-integration.yaml
=> gh-948: Update codecov action to v2

schema-builder/README.md
=> Add deprecation notice to schema builder README

python-shell/README.md
=> gh-951: Deprecate gafferpy

.github/workflows/continuous-integration.yaml, .github/workflows/create-alpha-release-branch.yaml, .github/workflows/create-hotfix-branch.yaml, .github/workflows/create-release-branch.yaml, .github/workflows/release-standalone.yaml, .github/workflows/release.yaml, .github/workflows/update-gaffer-version.yaml, cd/updateGafferVersion.sh
=> gh-953: Added release branches work

python-shell/src/gafferpy/gaffer_functions.py, python-shell/src/test/test_gaffer_functions_it.py, python-shell/src/test/test_gaffer_predicates_it.py
=> gh-957: Added functions and ignore generators

python-shell/src/gafferpy/gaffer_functions.py, python-shell/src/test/test_gaffer_functions.py
=> gh-961: Added missing ParseDate argument

mini-accumulo-cluster/src/main/java/uk/gov/gchq/gaffer/miniaccumulocluster/MiniAccumuloClusterController.java, mini-accumulo-cluster/src/main/java/uk/gov/gchq/gaffer/miniaccumulocluster/MiniAccumuloShellController.java, random-element-generation/src/main/java/uk/gov/gchq/gaffer/randomelementgeneration/cache/PreferentialAttachmentCache.java
* gh-984: Change usage of log4j to slf4j
- Resolve #988
=> gh-984: Change usage of log4j to slf4j (#985)

python-shell/README.md, ui/README.md
=> gh-998: Update links

mini-accumulo-cluster/src/test/java/uk/gov/gchq/gaffer/miniaccumulocluster/MiniAccumuloClusterControllerTest.java, performance-testing/performance-testing-accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/performancetesting/ingest/TestAccumuloStoreRandomElementIngestTest.java, performance-testing/performance-testing-core/src/test/java/uk/gov/gchq/gaffer/performancetesting/ingest/TestElementIngestTest.java, performance-testing/performance-testing-core/src/test/java/uk/gov/gchq/gaffer/performancetesting/ingest/TestQueryTest.java, random-element-generation/src/test/java/uk/gov/gchq/gaffer/randomelementgeneration/cache/TestPreferentialAttachmentCache.java, random-element-generation/src/test/java/uk/gov/gchq/gaffer/randomelementgeneration/cache/TestProbabilityGenerator.java, ui/src/test/java/uk/gov/gchq/gaffer/ui/QueryBuilderST.java
Also replace JUnit asserts with AssertJ.
- Resolve #832
=> Gh-832: Upgrade JUnit 4 to JUnit 5

ui/pom.xml
=> Gh-1008: Fix Selenium UI tests to work with new jersey

mini-accumulo-cluster/pom.xml, performance-testing/performance-testing-aws/pom.xml, performance-testing/performance-testing-aws/src/main/java/uk/gov/gchq/gaffer/performancetesting/aws/PublishAccumuloMetricsToCloudWatch.java
AWS changes not backwards compatible with Accumulo 1
- Resolve #1005
=> Gh-1005: Accumulo 2 update

ui/src/main/webapp/app/graph/graph-component.js, ui/src/main/webapp/app/graph/graph-service.js, ui/src/main/webapp/app/toolbar/toolbar-component.js, ui/src/test/webapp/app/graph/graph-component-spec.js, ui/src/test/webapp/app/graph/graph-service-spec.js
Cherry-pick of 7d90f3f3928e7c5230cf55dee9677107931c1a75 from #812
- Resolve #1010
=> Graph layout is now saved when navigate away from page (#812)

mini-accumulo-cluster/README.md
Update README to include more detail on building. Also add Windows details and improve heading usage.
- Resolve #935
=> Gh-935: MiniAccumuloCluster on Windows

python-shell/src/fishbowl/fishbowl.py, python-shell/src/fishbowl/templates/base.py.j2, python-shell/src/fishbowl/templates/config.py.j2, python-shell/src/fishbowl/templates/functions.py.j2, python-shell/src/fishbowl/templates/operations.py.j2, python-shell/src/gafferpy/generated_api/binary_operators.py, python-shell/src/gafferpy/generated_api/config.py, python-shell/src/gafferpy/generated_api/functions.py, python-shell/src/gafferpy/generated_api/operations.py, python-shell/src/gafferpy/generated_api/predicates.py
=> Gh 1018: Refactor fishbowl to use jinja2

python-shell/src/gafferpy/gaffer_types.py, python-shell/src/gafferpy_examples/example.py
=> Gh-1036: Added more types and examples for hllp

code-style/pmd-ruleset.xml, findbugs-exclude.xml, mini-accumulo-cluster/src/main/java/uk/gov/gchq/gaffer/miniaccumulocluster/MiniAccumuloClusterController.java, mini-accumulo-cluster/src/main/java/uk/gov/gchq/gaffer/miniaccumulocluster/MiniAccumuloClusterWithShellController.java, mini-accumulo-cluster/src/main/java/uk/gov/gchq/gaffer/miniaccumulocluster/MiniAccumuloShellController.java, performance-testing/performance-testing-accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/performancetesting/ingest/AccumuloElementIngestTest.java, performance-testing/performance-testing-accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/performancetesting/ingest/BytesWritableElementGenerator.java, performance-testing/performance-testing-aws/src/main/java/uk/gov/gchq/gaffer/performancetesting/aws/AwsEmrUtils.java, performance-testing/performance-testing-aws/src/main/java/uk/gov/gchq/gaffer/performancetesting/aws/CloudWatchMetricsListener.java, performance-testing/performance-testing-aws/src/main/java/uk/gov/gchq/gaffer/performancetesting/aws/PublishAccumuloMetricsToCloudWatch.java, performance-testing/performance-testing-core/src/main/java/uk/gov/gchq/gaffer/performancetesting/FileWriterMetricsListener.java, performance-testing/performance-testing-core/src/main/java/uk/gov/gchq/gaffer/performancetesting/TestProperties.java, performance-testing/performance-testing-core/src/main/java/uk/gov/gchq/gaffer/performancetesting/ingest/ElementIngestTest.java, performance-testing/performance-testing-core/src/main/java/uk/gov/gchq/gaffer/performancetesting/ingest/ElementIngestTestProperties.java, performance-testing/performance-testing-core/src/main/java/uk/gov/gchq/gaffer/performancetesting/query/QueryTest.java, performance-testing/performance-testing-core/src/main/java/uk/gov/gchq/gaffer/performancetesting/query/QueryTestProperties.java, random-element-generation/src/main/java/uk/gov/gchq/gaffer/randomelementgeneration/Constants.java, random-element-generation/src/main/java/uk/gov/gchq/gaffer/randomelementgeneration/cache/PreferentialAttachmentCache.java, random-element-generation/src/main/java/uk/gov/gchq/gaffer/randomelementgeneration/cache/ProbabilityGenerator.java, random-element-generation/src/main/java/uk/gov/gchq/gaffer/randomelementgeneration/supplier/ElementsSupplier.java, random-element-generation/src/main/java/uk/gov/gchq/gaffer/randomelementgeneration/supplier/ElementsSupplierWithRepeats.java, random-element-generation/src/main/java/uk/gov/gchq/gaffer/randomelementgeneration/supplier/EntitySeedSupplier.java, random-element-generation/src/main/java/uk/gov/gchq/gaffer/randomelementgeneration/supplier/RmatElementSupplier.java
=> Gh-1057: Fix code checking/quality

python-shell/src/gafferpy/gaffer_types.py
=> gh-1059: Fix gaffer_types hinting

.github/workflows/continuous-integration.yaml, .github/workflows/create-alpha-release-branch.yaml, .github/workflows/create-hotfix-branch.yaml, .github/workflows/create-release-branch.yaml, .github/workflows/release-standalone.yaml, .github/workflows/release.yaml
=> Gh-1072: Update Javadoc workflow
